import type {
  Repo
} from '@/types'

import { daysAgo } from './_shared'

export const SEED_REPOS: Repo[] = [
  {
    id: 'r1',
    slug: 'pdf-editor',
    name: 'PDF Editor',
    tagline: 'Edit PDF files directly in your browser',
    description: 'A free online PDF editor that lets you add text, images, highlights, and annotations to PDF documents without installing any software.',
    url: 'https://www.pdfescape.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pdfescape.com.ico',
    category: 'pdf',
    tags: ['pdf', 'editor', 'annotation', 'browser'],
    pricing: 'free',
    upvotes: 420,
    bookmarks: 130,
    submittedBy: 'u1',
    featured: true,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r2',
    slug: 'ilovepdf',
    name: 'iLovePDF',
    tagline: 'All-in-one online PDF toolkit',
    description: 'Merge, split, compress, convert, edit, and sign PDFs entirely in your browser. Trusted by millions of users worldwide for daily PDF tasks.',
    url: 'https://www.ilovepdf.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/ilovepdf.com.ico',
    category: 'pdf',
    tags: ['pdf', 'merge', 'compress', 'convert'],
    pricing: 'freemium',
    upvotes: 680,
    bookmarks: 210,
    submittedBy: 'u2',
    featured: true,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(0),
  },
  {
    id: 'r3',
    slug: 'smallpdf',
    name: 'Smallpdf',
    tagline: 'Compress, convert, and edit PDFs',
    description: 'Smallpdf offers a complete suite of PDF tools including compression, conversion between PDF and Office formats, e-signatures, and secure file sharing.',
    url: 'https://smallpdf.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/smallpdf.com.ico',
    category: 'pdf',
    tags: ['pdf', 'compress', 'convert', 'esign'],
    pricing: 'freemium',
    upvotes: 890,
    bookmarks: 280,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r4',
    slug: 'sejda',
    name: 'Sejda PDF',
    tagline: 'Simple and privacy-focused PDF editor',
    description: 'Edit, merge, split, and convert PDFs with a focus on privacy. Files are processed server-side but deleted after processing. No account required for most features.',
    url: 'https://www.sejda.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/sejda.com.ico',
    category: 'pdf',
    tags: ['pdf', 'editor', 'privacy', 'merge'],
    pricing: 'freemium',
    upvotes: 340,
    bookmarks: 95,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r5',
    slug: 'pdf24',
    name: 'PDF24',
    tagline: 'Free and versatile PDF utilities',
    description: 'A collection of over 25 free PDF tools including editor, compressor, converter, merger, and OCR. All tools are free to use with no daily limits.',
    url: 'https://tools.pdf24.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pdf24.org.ico',
    category: 'pdf',
    tags: ['pdf', 'tools', 'ocr', 'free'],
    pricing: 'free',
    upvotes: 510,
    bookmarks: 160,
    submittedBy: 'u5',
    featured: false,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r6',
    slug: 'canva',
    name: 'Canva',
    tagline: 'Online design and publishing platform',
    description: 'Create stunning designs, presentations, posters, and social media graphics with drag-and-drop tools. Features AI-powered design suggestions and a massive template library.',
    url: 'https://www.canva.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/canva.com.ico',
    category: 'design',
    tags: ['design', 'templates', 'presentations', 'social-media'],
    pricing: 'freemium',
    upvotes: 1950,
    bookmarks: 610,
    submittedBy: 'u1',
    featured: true,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(0),
  },
  {
    id: 'r7',
    slug: 'remove-bg',
    name: 'Remove.bg',
    tagline: 'AI-powered background removal for images',
    description: 'Automatically remove backgrounds from images with AI. Process portraits, product photos, and pets with high accuracy. API available for developers.',
    url: 'https://www.remove.bg',
    logoUrl: 'https://icons.duckduckgo.com/ip3/remove.bg.ico',
    category: 'image-editing',
    tags: ['background', 'images', 'ai', 'removal'],
    pricing: 'freemium',
    upvotes: 1200,
    bookmarks: 380,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(85),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r8',
    slug: 'tinypng',
    name: 'TinyPNG',
    tagline: 'Smart PNG and JPEG compression',
    description: 'Compress PNG and JPEG images while maintaining transparency and quality. Uses intelligent lossy compression to reduce file sizes significantly for web use.',
    url: 'https://tinypng.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/tinypng.com.ico',
    category: 'image-editing',
    tags: ['compression', 'png', 'jpeg', 'web'],
    pricing: 'free',
    upvotes: 760,
    bookmarks: 240,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r9',
    slug: 'pixlr',
    name: 'Pixlr',
    tagline: 'Free online photo editor',
    description: 'A browser-based photo editor that offers layers, filters, effects, and AI-powered tools. Includes Pixlr X (quick edits) and Pixlr E (advanced editing) modes.',
    url: 'https://pixlr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pixlr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editor', 'filters', 'browser'],
    pricing: 'freemium',
    upvotes: 580,
    bookmarks: 170,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r10',
    slug: 'photopea',
    name: 'Photopea',
    tagline: 'Advanced image editor in your browser',
    description: 'A full-featured photo editor that supports PSD, XCF, Sketch, and PDF formats. Offers layers, masks, blending modes, and advanced selection tools similar to Photoshop.',
    url: 'https://www.photopea.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photopea.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editor', 'psd', 'advanced'],
    pricing: 'free',
    upvotes: 920,
    bookmarks: 310,
    submittedBy: 'u5',
    featured: true,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r11',
    slug: 'cloudconvert',
    name: 'CloudConvert',
    tagline: 'Convert files between 200+ formats',
    description: 'A powerful file conversion service supporting documents, images, audio, video, and archives. Process files with customizable quality and size settings via web or API.',
    url: 'https://cloudconvert.com',
    logoUrl: 'https://www.google.com/s2/favicons?domain=cloudconvert.com&sz=64',
    category: 'converter',
    tags: ['convert', 'files', 'documents', 'api'],
    pricing: 'freemium',
    upvotes: 670,
    bookmarks: 190,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r12',
    slug: 'convertio',
    name: 'Convertio',
    tagline: 'Online file converter for any format',
    description: 'Convert documents, images, audio, video, and ebooks between formats. Batch processing supported with drag-and-drop interface. No registration required.',
    url: 'https://convertio.co',
    logoUrl: 'https://icons.duckduckgo.com/ip3/convertio.co.ico',
    category: 'converter',
    tags: ['convert', 'documents', 'images', 'batch'],
    pricing: 'freemium',
    upvotes: 440,
    bookmarks: 120,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r13',
    slug: 'online-convert',
    name: 'OnlineConvert',
    tagline: 'Free online file converter',
    description: 'A free file conversion service that supports video, audio, image, document, and archive formats. Offers URL import, cloud storage integration, and email delivery.',
    url: 'https://www.online-convert.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/online-convert.com.ico',
    category: 'converter',
    tags: ['convert', 'video', 'audio', 'free'],
    pricing: 'freemium',
    upvotes: 390,
    bookmarks: 100,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r14',
    slug: 'handbrake',
    name: 'HandBrake',
    tagline: 'Open-source video transcoder',
    description: 'A powerful open-source video transcoder for converting video files between formats. Supports batch processing, presets for devices, and advanced encoding options.',
    url: 'https://handbrake.fr',
    logoUrl: 'https://icons.duckduckgo.com/ip3/handbrake.fr.ico',
    category: 'converter',
    tags: ['video', 'transcode', 'open-source', 'desktop'],
    pricing: 'open-source',
    upvotes: 830,
    bookmarks: 260,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r15',
    slug: 'ffmpeg',
    name: 'FFmpeg',
    tagline: 'Complete multimedia framework',
    description: 'A cross-platform solution for recording, converting, and streaming audio and video. The industry standard command-line tool for media processing and manipulation.',
    url: 'https://ffmpeg.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/ffmpeg.org.ico',
    category: 'converter',
    tags: ['video', 'audio', 'cli', 'framework'],
    pricing: 'open-source',
    upvotes: 1100,
    bookmarks: 350,
    submittedBy: 'u5',
    featured: true,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r16',
    slug: 'excalidraw',
    name: 'Excalidraw',
    tagline: 'Virtual whiteboard for diagrams and sketches',
    description: 'A collaborative whiteboard tool for sketching diagrams, wireframes, and flowcharts. Features hand-drawn style, real-time collaboration, and end-to-end encryption.',
    url: 'https://excalidraw.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/excalidraw.com.ico',
    category: 'design',
    tags: ['whiteboard', 'diagrams', 'collaboration', 'sketch'],
    pricing: 'free',
    upvotes: 720,
    bookmarks: 230,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r17',
    slug: 'figma',
    name: 'Figma',
    tagline: 'Collaborative interface design tool',
    description: 'A cloud-based design tool for UI/UX design, prototyping, and collaboration. Enables real-time teamwork, design systems, and developer handoff with auto-layout.',
    url: 'https://www.figma.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/figma.com.ico',
    category: 'design',
    tags: ['design', 'ui', 'prototyping', 'collaboration'],
    pricing: 'freemium',
    upvotes: 2100,
    bookmarks: 680,
    submittedBy: 'u2',
    featured: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(0),
  },
  {
    id: 'r18',
    slug: 'gimp',
    name: 'GIMP',
    tagline: 'GNU Image Manipulation Program',
    description: 'A free and open-source raster graphics editor for photo retouching, image composition, and authoring. Supports layers, masks, filters, and extensible plugins.',
    url: 'https://www.gimp.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/gimp.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editor', 'open-source', 'desktop'],
    pricing: 'open-source',
    upvotes: 950,
    bookmarks: 290,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r19',
    slug: 'inkscape',
    name: 'Inkscape',
    tagline: 'Professional vector graphics editor',
    description: 'A free and open-source vector graphics editor for creating illustrations, icons, logos, and diagrams. Supports SVG format with advanced path and node editing.',
    url: 'https://inkscape.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/inkscape.org.ico',
    category: 'design',
    tags: ['vector', 'illustration', 'svg', 'open-source'],
    pricing: 'open-source',
    upvotes: 640,
    bookmarks: 190,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r20',
    slug: 'unsplash',
    name: 'Unsplash',
    tagline: 'Free high-resolution stock photos',
    description: 'Access a library of millions of free high-resolution images contributed by photographers worldwide. All photos are free to use for commercial and non-commercial projects.',
    url: 'https://unsplash.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/unsplash.com.ico',
    category: 'image-editing',
    tags: ['stock-photos', 'images', 'free', 'photography'],
    pricing: 'free',
    upvotes: 560,
    bookmarks: 180,
    submittedBy: 'u5',
    featured: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(7),
  },
  // Video tools
  {
    id: 'r21',
    slug: 'clipchamp',
    name: 'Clipchamp',
    tagline: 'Online video editor with templates',
    description: 'Microsoft\'s browser-based video editor with drag-and-drop timeline, filters, transitions, and text overlays. Export in 4K without watermarks.',
    url: 'https://clipchamp.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/clipchamp.com.ico',
    category: 'video',
    tags: ['video', 'editor', 'online', 'templates'],
    pricing: 'freemium',
    upvotes: 480,
    bookmarks: 140,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r22',
    slug: 'veed-io',
    name: 'VEED.io',
    tagline: 'Quick online video editing platform',
    description: 'Browser-based video editor for subtitles, trimming, filters, and audio. Popular for social media content with AI-powered features.',
    url: 'https://www.veed.io',
    logoUrl: 'https://icons.duckduckgo.com/ip3/veed.io.ico',
    category: 'video',
    tags: ['video', 'subtitles', 'editor', 'social-media'],
    pricing: 'freemium',
    upvotes: 620,
    bookmarks: 190,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r23',
    slug: 'kdenlive',
    name: 'Kdenlive',
    tagline: 'Open-source video editor for Linux/Windows',
    description: 'A powerful open-source multi-track video editor with effects, transitions, proxies, and color grading tools. Free and community-driven.',
    url: 'https://kdenlive.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/kdenlive.org.ico',
    category: 'video',
    tags: ['video', 'editor', 'open-source', 'desktop'],
    pricing: 'open-source',
    upvotes: 350,
    bookmarks: 95,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(10),
  },
  // Text tools
  {
    id: 'r24',
    slug: 'grammarly',
    name: 'Grammarly',
    tagline: 'AI writing assistant and grammar checker',
    description: 'An AI-powered writing assistant that checks grammar, spelling, tone, and clarity across documents, emails, and web browsers. Offers style suggestions and plagiarism detection.',
    url: 'https://grammarly.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/grammarly.com.ico',
    category: 'text',
    tags: ['writing', 'grammar', 'ai', 'assistant'],
    pricing: 'freemium',
    upvotes: 1850,
    bookmarks: 560,
    submittedBy: 'u4',
    featured: true,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(0),
  },
  {
    id: 'r25',
    slug: 'quillbot',
    name: 'QuillBot',
    tagline: 'AI paraphrasing and summarization tool',
    description: 'Paraphrase, summarize, and improve your writing with AI. Offers multiple modes for different writing styles, a grammar checker, and citation generator.',
    url: 'https://www.quillbot.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/quillbot.com.ico',
    category: 'text',
    tags: ['paraphrase', 'summarize', 'writing', 'grammar'],
    pricing: 'freemium',
    upvotes: 780,
    bookmarks: 240,
    submittedBy: 'u5',
    featured: false,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r26',
    slug: 'hemingway-editor',
    name: 'Hemingway Editor',
    tagline: 'Make your writing bold and clear',
    description: 'An editor that highlights complex sentences, passive voice, adverbs, and hard-to-read phrases. Helps improve readability and writing clarity.',
    url: 'https://hemingwayapp.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/hemingwayapp.com.ico',
    category: 'text',
    tags: ['writing', 'editor', 'readability', 'style'],
    pricing: 'freemium',
    upvotes: 440,
    bookmarks: 130,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(6),
  },
  // File tools
  {
    id: 'r27',
    slug: 'wetransfer',
    name: 'WeTransfer',
    tagline: 'Send large files easily',
    description: 'A simple file transfer service that lets you send up to 2GB for free. Files are encrypted in transit and available for download for 7 days.',
    url: 'https://wetransfer.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/wetransfer.com.ico',
    category: 'file',
    tags: ['file', 'transfer', 'sharing', 'cloud'],
    pricing: 'freemium',
    upvotes: 920,
    bookmarks: 280,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r28',
    slug: 'dropbox',
    name: 'Dropbox',
    tagline: 'Cloud storage and file synchronization',
    description: 'Store, sync, and share files across devices. Features file versioning, smart sync, paper documents, and team collaboration spaces.',
    url: 'https://dropbox.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/dropbox.com.ico',
    category: 'file',
    tags: ['cloud', 'storage', 'sync', 'collaboration'],
    pricing: 'freemium',
    upvotes: 1350,
    bookmarks: 410,
    submittedBy: 'u3',
    featured: true,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r29',
    slug: 'filezilla',
    name: 'FileZilla',
    tagline: 'Cross-platform FTP client',
    description: 'A free FTP, FTPS, and SFTP client for transferring files to and from servers. Features tabbed interface, site manager, and drag-and-drop support.',
    url: 'https://filezilla-project.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/filezilla-project.org.ico',
    category: 'file',
    tags: ['ftp', 'file', 'transfer', 'client'],
    pricing: 'free',
    upvotes: 380,
    bookmarks: 110,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(20),
  },
  {
    id: 'r30',
    slug: 'pdf-candy',
    name: 'PDF Candy',
    tagline: 'All-in-one online PDF toolkit with 40+ tools',
    description: 'A comprehensive online PDF editor offering 40+ tools including merge, split, compress, convert, edit, and OCR. Works entirely in the browser with no installation required.',
    url: 'https://pdfcandy.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pdfcandy.com.ico',
    category: 'pdf',
    tags: ['pdf', 'editor', 'converter', 'ocr'],
    pricing: 'freemium',
    upvotes: 340,
    bookmarks: 100,
    submittedBy: 'u3',
    featured: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r31',
    slug: 'squoosh',
    name: 'Squoosh',
    tagline: 'Modern image compression in your browser',
    description: 'A fast, offline-first image compression tool that lets you compare original and compressed images side by side. Supports WebP, AVIF, JPEG XL, and custom compression settings.',
    url: 'https://squoosh.app',
    logoUrl: 'https://icons.duckduckgo.com/ip3/squoosh.app.ico',
    category: 'image-editing',
    tags: ['image', 'compression', 'webp', 'avif'],
    pricing: 'free',
    upvotes: 510,
    bookmarks: 170,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r32',
    slug: 'svgomg',
    name: 'SVGOMG',
    tagline: 'SVG optimization with granular control',
    description: 'A web-based SVG optimizer that removes unnecessary metadata, reduces file sizes, and cleans up SVG code. Features real-time preview, precision controls, and downloadable optimized files.',
    url: 'https://svgomg.net',
    logoUrl: 'https://icons.duckduckgo.com/ip3/svgomg.net.ico',
    category: 'image-editing',
    tags: ['svg', 'optimization', 'minification', 'vector'],
    pricing: 'free',
    upvotes: 380,
    bookmarks: 120,
    submittedBy: 'u5',
    featured: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r33',
    slug: 'zamzar',
    name: 'Zamzar',
    tagline: 'Online file conversion supporting 1200+ formats',
    description: 'A versatile file conversion service that supports documents, images, audio, video, and archives. Simple drag-and-drop interface with email delivery and API access for developers.',
    url: 'https://www.zamzar.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/zamzar.com.ico',
    category: 'converter',
    tags: ['converter', 'file', 'document', 'video'],
    pricing: 'freemium',
    upvotes: 360,
    bookmarks: 110,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r34',
    slug: 'penpot',
    name: 'Penpot',
    tagline: 'Open-source design and prototyping platform',
    description: 'The first open-source design tool that bridges the gap between designers and developers. Offers vector design, prototyping, design systems, and developer handoff - all in the browser.',
    url: 'https://penpot.app',
    logoUrl: 'https://icons.duckduckgo.com/ip3/penpot.app.ico',
    category: 'design',
    tags: ['design', 'prototyping', 'vector', 'open-source'],
    pricing: 'open-source',
    upvotes: 490,
    bookmarks: 170,
    submittedBy: 'u4',
    featured: true,
    featuredDate: daysAgo(1),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r35',
    slug: 'blender',
    name: 'Blender',
    tagline: 'Professional open-source 3D creation suite',
    description: 'A complete 3D creation pipeline for modeling, rigging, animation, simulation, rendering, compositing, and motion tracking. Used by artists and studios worldwide for films, games, and visual effects.',
    url: 'https://www.blender.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/blender.org.ico',
    category: 'design',
    tags: ['3d', 'animation', 'modeling', 'rendering'],
    pricing: 'open-source',
    upvotes: 820,
    bookmarks: 290,
    submittedBy: 'u3',
    featured: true,
    featuredDate: daysAgo(6),
    createdAt: daysAgo(1000),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r36',
    slug: 'davinci-resolve',
    name: 'DaVinci Resolve',
    tagline: 'Professional video editing and color grading',
    description: 'An industry-standard video editing and color correction tool used in Hollywood productions. Features advanced color grading, audio post-production, visual effects, and motion graphics - all in one app.',
    url: 'https://www.blackmagicdesign.com/products/davinciresolve',
    logoUrl: 'https://icons.duckduckgo.com/ip3/blackmagicdesign.com.ico',
    category: 'video',
    tags: ['video', 'editing', 'color-grading', 'post-production'],
    pricing: 'free',
    upvotes: 740,
    bookmarks: 260,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r37',
    slug: 'obs-studio',
    name: 'OBS Studio',
    tagline: 'Free and open-source recording and live streaming',
    description: 'A powerful screen recorder and live streaming application with customizable scenes, audio mixing, transitions, and plugin support. The industry standard for game streaming and desktop recording.',
    url: 'https://obsproject.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/obsproject.com.ico',
    category: 'video',
    tags: ['video', 'streaming', 'recording', 'screencast'],
    pricing: 'open-source',
    upvotes: 650,
    bookmarks: 210,
    submittedBy: 'u5',
    featured: false,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r38',
    slug: 'deepl-write',
    name: 'DeepL Write',
    tagline: 'AI-powered writing assistant for clear, natural text',
    description: 'An AI writing tool that helps improve your writing by suggesting alternative phrasing, adjusting tone, and fixing grammar. Supports English, German, French, Spanish, and more with context-aware suggestions.',
    url: 'https://www.deepl.com/write',
    logoUrl: 'https://icons.duckduckgo.com/ip3/deepl.com.ico',
    category: 'text',
    tags: ['writing', 'grammar', 'ai', 'proofreading'],
    pricing: 'freemium',
    upvotes: 370,
    bookmarks: 120,
    submittedBy: 'u2',
    featured: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r39',
    slug: 'languagetool',
    name: 'LanguageTool',
    tagline: 'Open-source grammar and style checker in 30+ languages',
    description: 'A multilingual proofreading tool that checks grammar, style, and spelling in over 30 languages. Available as a browser extension, desktop app, and API integration.',
    url: 'https://languagetool.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/languagetool.org.ico',
    category: 'text',
    tags: ['grammar', 'spelling', 'writing', 'proofreading'],
    pricing: 'freemium',
    upvotes: 310,
    bookmarks: 95,
    submittedBy: 'u4',
    featured: false,
    createdAt: daysAgo(250),
    updatedAt: daysAgo(7),
  },
  {
    id: 'r40',
    slug: 'google-drive',
    name: 'Google Drive',
    tagline: 'Cloud storage and file sharing with Google ecosystem',
    description: 'A cloud storage service tightly integrated with Google Workspace (Docs, Sheets, Slides). Offers 15 GB free storage, real-time collaboration, version history, and powerful search across all your files.',
    url: 'https://drive.google.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/drive.google.com.ico',
    category: 'file',
    tags: ['cloud', 'storage', 'collaboration', 'sync'],
    pricing: 'freemium',
    upvotes: 920,
    bookmarks: 330,
    submittedBy: 'u3',
    featured: true,
    featuredDate: daysAgo(4),
    createdAt: daysAgo(800),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r41',
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    tagline: 'Free customizable QR codes with tracking and analytics',
    description: 'Generate QR codes for URLs, text, WiFi, vCards, and more. Customize colors, add logos, and track scan statistics. No account required for basic generation.',
    url: 'https://www.qr-code-generator.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/qr-code-generator.com.ico',
    category: 'other',
    tags: ['qr-code', 'generator', 'scanner', 'marketing'],
    pricing: 'free',
    upvotes: 280,
    bookmarks: 80,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r43',
    slug: 'photosense',
    name: 'Photosense',
    tagline: 'Quick batch photo enhancement for Mac & iOS',
    description: `Quick batch photo enhancement for Mac & iOS.`,
    url: 'https://photosense.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photosense.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 149,
    bookmarks: 30,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(154),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r44',
    slug: 'perfectly-clear',
    name: 'Perfectly Clear',
    tagline: 'AI photo editor with automatic correction presets',
    description: `AI photo editor with automatic correction presets.`,
    url: 'https://www.perfectlyclear.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.perfectlyclear.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 160,
    bookmarks: 61,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(274),
    updatedAt: daysAgo(18),
  },
  {
    id: 'r45',
    slug: 'akvis-enhancer',
    name: 'Akvis Enhancer',
    tagline: 'Photo enhancement with detail and contrast improvement',
    description: `Photo enhancement with detail and contrast improvement.`,
    url: 'https://akvis.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/akvis.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 134,
    bookmarks: 49,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(143),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r46',
    slug: 'enhance-photo',
    name: 'Enhance Pho.to',
    tagline: 'Free online photo enhancer with noise and color fixes',
    description: `Free online photo enhancer with noise and color fixes.`,
    url: 'https://enhance.pho.to',
    logoUrl: 'https://icons.duckduckgo.com/ip3/enhance.pho.to.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 139,
    bookmarks: 21,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(279),
    updatedAt: daysAgo(19),
  },
  {
    id: 'r47',
    slug: 'ashampoo-photo-optimizer',
    name: 'Ashampoo Photo Optimizer',
    tagline: 'One-click photo optimizer for Windows',
    description: `One-click photo optimizer for Windows.`,
    url: 'https://www.ashampoo.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.ashampoo.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 199,
    bookmarks: 11,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(138),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r49',
    slug: 'algorithmia',
    name: 'Algorithmia',
    tagline: 'AI black-and-white photo colorization',
    description: `AI black-and-white photo colorization.`,
    url: 'https://algorithmia.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/algorithmia.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 98,
    bookmarks: 32,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(18),
  },
  {
    id: 'r50',
    slug: 'fotojet',
    name: 'Fotojet',
    tagline: 'Online photo editor and collage maker',
    description: `Online photo editor and collage maker.`,
    url: 'https://fotojet.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/fotojet.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 189,
    bookmarks: 6,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(181),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r52',
    slug: 'fotor',
    name: 'Fotor',
    tagline: 'Online photo editor and design platform',
    description: `Online photo editor and design platform.`,
    url: 'https://www.fotor.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.fotor.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 33,
    bookmarks: 62,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(240),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r54',
    slug: 'preloadr',
    name: 'Preloadr',
    tagline: 'Flickr-specific photo editing tool',
    description: `Flickr-specific photo editing tool.`,
    url: 'https://preloadr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/preloadr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 89,
    bookmarks: 6,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(348),
    updatedAt: daysAgo(30),
  },
  {
    id: 'r55',
    slug: 'lunapic',
    name: 'Lunapic',
    tagline: 'Simple free online photo editor',
    description: `Simple free online photo editor.`,
    url: 'https://lunapic.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/lunapic.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 214,
    bookmarks: 47,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(115),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r56',
    slug: 'picture2life',
    name: 'Picture2life',
    tagline: 'Ajax-based online photo editor',
    description: `Ajax-based online photo editor.`,
    url: 'https://picture2life.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/picture2life.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 135,
    bookmarks: 60,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(291),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r57',
    slug: 'picsio',
    name: 'Pics.io',
    tagline: 'Simple online photo editor',
    description: `Simple online photo editor.`,
    url: 'https://pics.io',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pics.io.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 89,
    bookmarks: 63,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(114),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r58',
    slug: 'ribbet',
    name: 'Ribbet',
    tagline: 'Free online photo editor',
    description: `Free online photo editor.`,
    url: 'https://ribbet.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/ribbet.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 97,
    bookmarks: 28,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(165),
    updatedAt: daysAgo(12),
  },
  {
    id: 'r59',
    slug: 'picmonkey',
    name: 'PicMonkey',
    tagline: 'Popular online photo editor',
    description: `Popular online photo editor.`,
    url: 'https://www.picmonkey.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.picmonkey.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 179,
    bookmarks: 26,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(224),
    updatedAt: daysAgo(21),
  },
  {
    id: 'r60',
    slug: 'befunky',
    name: 'Befunky',
    tagline: 'Online photo editor and collage maker',
    description: `Online photo editor and collage maker.`,
    url: 'https://www.befunky.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.befunky.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 129,
    bookmarks: 46,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(240),
    updatedAt: daysAgo(30),
  },
  {
    id: 'r61',
    slug: 'photo',
    name: 'pho.to',
    tagline: 'Online photo editor with preset effects',
    description: `Online photo editor with preset effects.`,
    url: 'https://pho.to',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pho.to.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 59,
    bookmarks: 58,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(326),
    updatedAt: daysAgo(27),
  },
  {
    id: 'r62',
    slug: 'pizap',
    name: 'piZap',
    tagline: 'Online photo editor and collage maker',
    description: `Online photo editor and collage maker.`,
    url: 'https://pizap.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pizap.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 99,
    bookmarks: 22,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(266),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r64',
    slug: 'avatan',
    name: 'Avatan',
    tagline: 'Free online photo editor and collage maker',
    description: `Free online photo editor and collage maker.`,
    url: 'https://avatan.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/avatan.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 99,
    bookmarks: 49,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(235),
    updatedAt: daysAgo(23),
  },
  {
    id: 'r65',
    slug: 'fotoflexer',
    name: 'FotoFlexer',
    tagline: 'Online photo editor with advanced effects',
    description: `Online photo editor with advanced effects.`,
    url: 'https://fotoflexer.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/fotoflexer.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 99,
    bookmarks: 27,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(86),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r67',
    slug: 'picsart',
    name: 'PicsArt',
    tagline: 'Mobile photo editing, collage and drawing app',
    description: `Mobile photo editing, collage and drawing app.`,
    url: 'https://picsart.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/picsart.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 40,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(324),
    updatedAt: daysAgo(27),
  },
  {
    id: 'r68',
    slug: 'gmic',
    name: 'G\'MIC',
    tagline: 'Full-featured image processing framework with GIMP plugin',
    description: `Full-featured image processing framework with GIMP plugin.`,
    url: 'https://gmic.eu',
    logoUrl: 'https://icons.duckduckgo.com/ip3/gmic.eu.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 148,
    bookmarks: 28,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(290),
    updatedAt: daysAgo(22),
  },
  {
    id: 'r69',
    slug: 'pinta',
    name: 'Pinta',
    tagline: 'Open-source drawing and image editor',
    description: `Open-source drawing and image editor.`,
    url: 'https://pinta-project.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pinta-project.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 200,
    bookmarks: 63,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(53),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r71',
    slug: 'paintnet',
    name: 'Paint.net',
    tagline: 'Free image and photo editing for PC',
    description: `Free image and photo editing for PC.`,
    url: 'https://www.getpaint.net',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.getpaint.net.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 180,
    bookmarks: 16,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(124),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r72',
    slug: 'krita',
    name: 'Krita',
    tagline: 'Open-source digital painting studio',
    description: `Open-source digital painting studio.`,
    url: 'https://krita.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/krita.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 151,
    bookmarks: 47,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(99),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r73',
    slug: 'imagemagick',
    name: 'Imagemagick',
    tagline: 'CLI image processing suite',
    description: `CLI image processing suite.`,
    url: 'https://imagemagick.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/imagemagick.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 180,
    bookmarks: 32,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(162),
    updatedAt: daysAgo(28),
  },
  {
    id: 'r76',
    slug: 'photodemon',
    name: 'Photodemon',
    tagline: 'Free portable photo editor for Windows',
    description: `Free portable photo editor for Windows.`,
    url: 'https://photodemon.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photodemon.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 43,
    bookmarks: 51,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(210),
    updatedAt: daysAgo(29),
  },
  {
    id: 'r77',
    slug: 'adobe-photoshop',
    name: 'Adobe Photoshop',
    tagline: 'Industry-standard photo editing software',
    description: `Industry-standard photo editing software.`,
    url: 'https://www.photoshop.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.photoshop.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 178,
    bookmarks: 54,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(69),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r78',
    slug: 'adobe-lightroom',
    name: 'Adobe Lightroom',
    tagline: 'Professional photo processor and organizer',
    description: `Professional photo processor and organizer.`,
    url: 'https://www.lightroom.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.lightroom.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 194,
    bookmarks: 32,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(194),
    updatedAt: daysAgo(20),
  },
  {
    id: 'r79',
    slug: 'capture-one',
    name: 'Capture One',
    tagline: 'Professional RAW photo editing software',
    description: `Professional RAW photo editing software.`,
    url: 'https://www.captureone.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.captureone.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 130,
    bookmarks: 51,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(221),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r80',
    slug: 'luminar',
    name: 'Luminar',
    tagline: 'AI-powered photo editor for Mac and Windows',
    description: `AI-powered photo editor for Mac and Windows.`,
    url: 'https://skylum.com/luminar',
    logoUrl: 'https://icons.duckduckgo.com/ip3/skylum.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 126,
    bookmarks: 45,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(177),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r81',
    slug: 'radlab',
    name: 'Radlab',
    tagline: 'Photo editor with curated effects',
    description: `Photo editor with curated effects.`,
    url: 'https://radlab.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/radlab.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 109,
    bookmarks: 55,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(241),
    updatedAt: daysAgo(19),
  },
  {
    id: 'r82',
    slug: 'affinity-photo',
    name: 'Affinity Photo',
    tagline: 'Professional photo editing for Mac',
    description: `Professional photo editing for Mac.`,
    url: 'https://affinity.serif.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/affinity.serif.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 190,
    bookmarks: 25,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(276),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r83',
    slug: 'dxo-photo-suite',
    name: 'DXO Photo Suite',
    tagline: 'Powerful photo editing software suite',
    description: `Powerful photo editing software suite.`,
    url: 'https://www.dxo.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.dxo.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 136,
    bookmarks: 16,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(94),
    updatedAt: daysAgo(24),
  },
  {
    id: 'r84',
    slug: 'pixelmator',
    name: 'Pixelmator',
    tagline: 'Powerful image editor for Mac',
    description: `Powerful image editor for Mac.`,
    url: 'https://www.pixelmator.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.pixelmator.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 143,
    bookmarks: 56,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(189),
    updatedAt: daysAgo(28),
  },
  {
    id: 'r85',
    slug: 'on1-photo',
    name: 'On1 Photo',
    tagline: 'Professional photo editor with easy interface',
    description: `Professional photo editor with easy interface.`,
    url: 'https://www.on1.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.on1.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 53,
    bookmarks: 53,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r86',
    slug: 'corel-aftershot-pro',
    name: 'Corel AfterShot Pro',
    tagline: 'Professional RAW photo processor',
    description: `Professional RAW photo processor.`,
    url: 'https://www.corel.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.corel.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 137,
    bookmarks: 55,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(281),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r87',
    slug: 'zoner-photo-studio',
    name: 'Zoner Photo Studio',
    tagline: 'All-in-one photo software for Windows',
    description: `All-in-one photo software for Windows.`,
    url: 'https://www.zoner.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.zoner.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 101,
    bookmarks: 18,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(12),
  },
  {
    id: 'r88',
    slug: 'acorn',
    name: 'Acorn',
    tagline: 'Lightweight image editor for macOS',
    description: `Lightweight image editor for macOS.`,
    url: 'https://flyingmeat.com/acorn',
    logoUrl: 'https://icons.duckduckgo.com/ip3/flyingmeat.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 221,
    bookmarks: 21,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(305),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r89',
    slug: 'picktorial',
    name: 'Picktorial',
    tagline: 'Non-destructive RAW editor for Mac',
    description: `Non-destructive RAW editor for Mac.`,
    url: 'https://picktorial.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/picktorial.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 35,
    bookmarks: 43,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(316),
    updatedAt: daysAgo(16),
  },
  {
    id: 'r90',
    slug: 'photomizer',
    name: 'Photomizer',
    tagline: 'Photo optimization and repair software',
    description: `Photo optimization and repair software.`,
    url: 'https://www.photomizer.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.photomizer.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 74,
    bookmarks: 10,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(146),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r92',
    slug: 'photoline',
    name: 'PhotoLine',
    tagline: 'Raster and vector graphics editor',
    description: `Raster and vector graphics editor.`,
    url: 'https://www.pl32.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.pl32.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 50,
    bookmarks: 16,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(162),
    updatedAt: daysAgo(13),
  },
  {
    id: 'r93',
    slug: 'inpixio',
    name: 'Inpixio',
    tagline: 'Photo editing suite with object removal',
    description: `Photo editing suite with object removal.`,
    url: 'https://www.inpixio.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.inpixio.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 150,
    bookmarks: 17,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(224),
    updatedAt: daysAgo(23),
  },
  {
    id: 'r94',
    slug: 'photo-lab',
    name: 'Photo Lab',
    tagline: 'Photo editing software with effects',
    description: `Photo editing software with effects.`,
    url: 'https://photolab.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photolab.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 63,
    bookmarks: 29,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(167),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r96',
    slug: 'aurora-hdr',
    name: 'Aurora HDR',
    tagline: 'HDR photo editor for Mac',
    description: `HDR photo editor for Mac.`,
    url: 'https://aurorahdr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/aurorahdr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 47,
    bookmarks: 47,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(227),
    updatedAt: daysAgo(21),
  },
  {
    id: 'r99',
    slug: 'photo-kako',
    name: 'Photo-kako',
    tagline: 'Free online HDR photo editor',
    description: `Free online HDR photo editor.`,
    url: 'https://photo-kako.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photo-kako.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 77,
    bookmarks: 9,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r101',
    slug: 'hydra',
    name: 'Hydra',
    tagline: 'HDR image creation and editing',
    description: `HDR image creation and editing.`,
    url: 'https://www.hydra.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.hydra.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 170,
    bookmarks: 20,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(113),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r103',
    slug: 'easyhdr',
    name: 'EasyHDR',
    tagline: 'Easy HDR image processing software',
    description: `Easy HDR image processing software.`,
    url: 'https://easyhdr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/easyhdr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 99,
    bookmarks: 31,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(215),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r106',
    slug: 'luminancehdr',
    name: 'LuminanceHDR',
    tagline: 'Open-source HDR imaging workflow',
    description: `Open-source HDR imaging workflow.`,
    url: 'https://luminancehdr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/luminancehdr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 30,
    bookmarks: 6,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(210),
    updatedAt: daysAgo(22),
  },
  {
    id: 'r107',
    slug: 'hdrmerge',
    name: 'HDRMerge',
    tagline: 'Free HDR raw image merging software',
    description: `Free HDR raw image merging software.`,
    url: 'https://hdrmerge.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/hdrmerge.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 102,
    bookmarks: 12,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r109',
    slug: 'machinery-hdr',
    name: 'Machinery HDR',
    tagline: 'Easy and powerful HDR photo editor',
    description: `Easy and powerful HDR photo editor.`,
    url: 'https://machineryhdr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/machineryhdr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 186,
    bookmarks: 56,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(140),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r110',
    slug: 'polarr',
    name: 'Polarr',
    tagline: 'Cross-platform pro photo editor',
    description: `Cross-platform pro photo editor.`,
    url: 'https://www.polarr.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.polarr.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 137,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(104),
    updatedAt: daysAgo(7),
  },
  {
    id: 'r112',
    slug: 'creative-kit',
    name: 'Creative Kit',
    tagline: 'Photography app pack with 500+ creative tools',
    description: `Photography app pack with 500+ creative tools.`,
    url: 'https://creativekit.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/creativekit.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 115,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r113',
    slug: 'on1-effects',
    name: 'On1 Effects',
    tagline: 'Selective photo effects filtering',
    description: `Selective photo effects filtering.`,
    url: 'https://www.on1.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.on1.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 126,
    bookmarks: 36,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(29),
  },
  {
    id: 'r114',
    slug: 'rollip',
    name: 'Rollip',
    tagline: 'High-quality free photo effects',
    description: `High-quality free photo effects.`,
    url: 'https://rollip.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/rollip.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 156,
    bookmarks: 38,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(69),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r117',
    slug: 'topaz-labs',
    name: 'Topaz Labs',
    tagline: 'AI-powered photo editing plugins',
    description: `AI-powered photo editing plugins.`,
    url: 'https://topazlabs.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/topazlabs.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 185,
    bookmarks: 17,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(264),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r118',
    slug: 'eye-candy',
    name: 'Eye Candy',
    tagline: 'Realistic Photoshop effects plugin',
    description: `Realistic Photoshop effects plugin.`,
    url: 'https://www.eye-candy.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.eye-candy.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 60,
    bookmarks: 25,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(177),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r119',
    slug: 'blow-up',
    name: 'Blow Up',
    tagline: 'Photo enlargement without quality loss',
    description: `Photo enlargement without quality loss.`,
    url: 'https://www.blow-up.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.blow-up.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 218,
    bookmarks: 14,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(310),
    updatedAt: daysAgo(27),
  },
  {
    id: 'r120',
    slug: 'instagram',
    name: 'Instagram',
    tagline: 'Popular photo sharing and editing app',
    description: `Popular photo sharing and editing app.`,
    url: 'https://www.instagram.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.instagram.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 83,
    bookmarks: 14,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(348),
    updatedAt: daysAgo(13),
  },
  {
    id: 'r123',
    slug: 'vsco-cam',
    name: 'VSCO Cam',
    tagline: 'Photo editor with film-quality presets',
    description: `Photo editor with film-quality presets.`,
    url: 'https://vsco.co',
    logoUrl: 'https://icons.duckduckgo.com/ip3/vsco.co.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 46,
    bookmarks: 44,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(111),
    updatedAt: daysAgo(23),
  },
  {
    id: 'r125',
    slug: 'photo-lab-picture-editor',
    name: 'Photo Lab Picture Editor',
    tagline: 'Photo effects and collage editor',
    description: `Photo effects and collage editor.`,
    url: 'https://photolab.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photolab.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 74,
    bookmarks: 46,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(339),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r129',
    slug: 'lightx',
    name: 'LightX',
    tagline: 'Advanced photo editor with cutout',
    description: `Advanced photo editor with cutout.`,
    url: 'https://www.lightx.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.lightx.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 110,
    bookmarks: 23,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(97),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r134',
    slug: 'lensical',
    name: 'Lensical',
    tagline: 'Face effect filters for iPhone',
    description: `Face effect filters for iPhone.`,
    url: 'https://lensical.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/lensical.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 158,
    bookmarks: 46,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(285),
    updatedAt: daysAgo(27),
  },
  {
    id: 'r137',
    slug: 'adobe-photoshop-express',
    name: 'Adobe Photoshop Express',
    tagline: 'Adobe mobile photo editor for iOS/Android',
    description: `Adobe mobile photo editor for iOS/Android.`,
    url: 'https://www.adobe.com',
    logoUrl: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 145,
    bookmarks: 26,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(219),
    updatedAt: daysAgo(10),
  },
  {
    id: 'r141',
    slug: 'camera360',
    name: 'Camera360',
    tagline: 'Smart camera with scene detection',
    description: `Smart camera with scene detection.`,
    url: 'https://camera360.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/camera360.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 220,
    bookmarks: 35,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(327),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r142',
    slug: 'instasize',
    name: 'InstaSize',
    tagline: 'Instagram companion app without cropping',
    description: `Instagram companion app without cropping.`,
    url: 'https://instasize.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/instasize.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 61,
    bookmarks: 33,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(241),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r143',
    slug: 'photo-editor',
    name: 'Photo Editor',
    tagline: 'Robust mobile photo manipulation tool',
    description: `Robust mobile photo manipulation tool.`,
    url: 'https://photoeditor.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photoeditor.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 193,
    bookmarks: 45,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(62),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r144',
    slug: 'photo-studio',
    name: 'Photo Studio',
    tagline: 'Professional mobile photo editing studio',
    description: `Professional mobile photo editing studio.`,
    url: 'https://photostudio.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photostudio.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 220,
    bookmarks: 17,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(263),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r145',
    slug: 'photo-editor-by-inpixio',
    name: 'Photo Editor by Inpixio',
    tagline: 'iOS photo editor with professional tools',
    description: `iOS photo editor with professional tools.`,
    url: 'https://www.inpixio.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.inpixio.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 147,
    bookmarks: 55,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(53),
    updatedAt: daysAgo(19),
  },
  {
    id: 'r146',
    slug: 'preset',
    name: 'Preset',
    tagline: 'iOS custom photo filter creator',
    description: `iOS custom photo filter creator.`,
    url: 'https://preset.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/preset.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 206,
    bookmarks: 29,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(190),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r147',
    slug: 'magic-picture',
    name: 'Magic Picture',
    tagline: 'Photo enhancement and compression app',
    description: `Photo enhancement and compression app.`,
    url: 'https://magicpicture.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/magicpicture.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 99,
    bookmarks: 40,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(253),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r148',
    slug: 'touchretouch',
    name: 'TouchRetouch',
    tagline: 'Remove unwanted objects from photos',
    description: `Remove unwanted objects from photos.`,
    url: 'https://www.touchretouch.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.touchretouch.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 194,
    bookmarks: 14,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(203),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r150',
    slug: 'picsay-pro',
    name: 'Picsay Pro',
    tagline: 'Award-winning Android photo editor',
    description: `Award-winning Android photo editor.`,
    url: 'https://picsaypro.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/picsaypro.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 85,
    bookmarks: 41,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(290),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r151',
    slug: 'raw-picsio',
    name: 'RAW Pics.io',
    tagline: 'In-browser RAW file viewer and converter',
    description: `In-browser RAW file viewer and converter.`,
    url: 'https://raw.pics.io',
    logoUrl: 'https://icons.duckduckgo.com/ip3/raw.pics.io.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 161,
    bookmarks: 34,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(187),
    updatedAt: daysAgo(20),
  },
  {
    id: 'r152',
    slug: 'rawtherapee',
    name: 'Rawtherapee',
    tagline: 'Open-source RAW image processing',
    description: `Open-source RAW image processing.`,
    url: 'https://rawtherapee.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/rawtherapee.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 219,
    bookmarks: 34,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(261),
    updatedAt: daysAgo(12),
  },
  {
    id: 'r153',
    slug: 'darktable',
    name: 'Darktable',
    tagline: 'Open-source photography workflow and RAW developer',
    description: `Open-source photography workflow and RAW developer.`,
    url: 'https://www.darktable.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.darktable.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 228,
    bookmarks: 42,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r154',
    slug: 'ufraw',
    name: 'UFRaw',
    tagline: 'RAW image utility for GIMP',
    description: `RAW image utility for GIMP.`,
    url: 'https://ufraw.sourceforge.net',
    logoUrl: 'https://icons.duckduckgo.com/ip3/ufraw.sourceforge.net.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 130,
    bookmarks: 56,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(343),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r155',
    slug: 'photivo',
    name: 'Photivo',
    tagline: 'Non-destructive RAW and bitmap processor',
    description: `Non-destructive RAW and bitmap processor.`,
    url: 'https://photivo.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photivo.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 219,
    bookmarks: 17,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(21),
  },
  {
    id: 'r156',
    slug: 'filmulator',
    name: 'Filmulator',
    tagline: 'Streamlined RAW editor with film simulation',
    description: `Streamlined RAW editor with film simulation.`,
    url: 'https://filmulator.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/filmulator.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 31,
    bookmarks: 42,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(97),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r160',
    slug: 'iridient-developer',
    name: 'Iridient Developer',
    tagline: 'Powerful RAW conversion for Mac',
    description: `Powerful RAW conversion for Mac.`,
    url: 'https://iridient.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/iridient.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 223,
    bookmarks: 63,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(254),
    updatedAt: daysAgo(3),
  },
  {
    id: 'r162',
    slug: 'rawdigger',
    name: 'RawDigger',
    tagline: 'RAW image analyzer tool',
    description: `RAW image analyzer tool.`,
    url: 'https://rawdigger.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/rawdigger.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 201,
    bookmarks: 59,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(157),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r163',
    slug: 'fastrawviewer',
    name: 'Fastrawviewer',
    tagline: 'WYSIWYG RAW image viewer',
    description: `WYSIWYG RAW image viewer.`,
    url: 'https://fastrawviewer.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/fastrawviewer.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 118,
    bookmarks: 64,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(229),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r164',
    slug: 'silkypix',
    name: 'Silkypix',
    tagline: 'Professional RAW development software',
    description: `Professional RAW development software.`,
    url: 'https://silkypix.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/silkypix.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 209,
    bookmarks: 9,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(114),
    updatedAt: daysAgo(18),
  },
  {
    id: 'r165',
    slug: 'exposure-x2',
    name: 'Exposure X2',
    tagline: 'Creative photo editor and organizer',
    description: `Creative photo editor and organizer.`,
    url: 'https://exposure.software',
    logoUrl: 'https://icons.duckduckgo.com/ip3/exposure.software.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 201,
    bookmarks: 25,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(277),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r166',
    slug: 'canon-digital-photo-professional',
    name: 'Canon Digital Photo Professional',
    tagline: 'Canon free RAW image processor',
    description: `Canon free RAW image processor.`,
    url: 'https://www.canon.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/canon.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 185,
    bookmarks: 13,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(87),
    updatedAt: daysAgo(21),
  },
  {
    id: 'r167',
    slug: 'hasselblad-phocus',
    name: 'Hasselblad Phocus',
    tagline: 'Hasselblad free RAW processing software',
    description: `Hasselblad free RAW processing software.`,
    url: 'https://www.hasselblad.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/hasselblad.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 83,
    bookmarks: 34,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(311),
    updatedAt: daysAgo(18),
  },
  {
    id: 'r168',
    slug: 'portraiture',
    name: 'Portraiture',
    tagline: 'Professional skin retouching plugin',
    description: `Professional skin retouching plugin.`,
    url: 'https://portraiture.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/portraiture.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 147,
    bookmarks: 50,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(76),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r169',
    slug: 'portraitpro',
    name: 'PortraitPro',
    tagline: 'Portrait enhancement and retouching software',
    description: `Portrait enhancement and retouching software.`,
    url: 'https://portraitpro.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/portraitpro.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 201,
    bookmarks: 24,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(319),
    updatedAt: daysAgo(18),
  },
  {
    id: 'r170',
    slug: 'pinkmirror',
    name: 'PinkMirror',
    tagline: 'Online face retouching and beauty app',
    description: `Online face retouching and beauty app.`,
    url: 'https://pinkmirror.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pinkmirror.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 192,
    bookmarks: 32,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(109),
    updatedAt: daysAgo(15),
  },
  {
    id: 'r172',
    slug: 'adobe-photoshop-fix',
    name: 'Adobe Photoshop Fix',
    tagline: 'Adobe app for photo retouching on mobile',
    description: `Adobe app for photo retouching on mobile.`,
    url: 'https://www.adobe.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.adobe.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 42,
    bookmarks: 27,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(223),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r174',
    slug: 'zerene-stacker',
    name: 'Zerene Stacker',
    tagline: 'Focus stacking for macro photography',
    description: `Focus stacking for macro photography.`,
    url: 'https://zerene.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/zerene.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 105,
    bookmarks: 19,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(84),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r175',
    slug: 'helicon-focus',
    name: 'Helicon Focus',
    tagline: 'Focus stacking to increase depth-of-field',
    description: `Focus stacking to increase depth-of-field.`,
    url: 'https://www.heliconsoft.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.heliconsoft.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 110,
    bookmarks: 11,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r176',
    slug: 'vivid-fix',
    name: 'Vivid Fix',
    tagline: 'Fix underwater and restore old photos',
    description: `Fix underwater and restore old photos.`,
    url: 'https://vividfix.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/vividfix.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 158,
    bookmarks: 52,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(182),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r178',
    slug: 'focus-magic',
    name: 'Focus Magic',
    tagline: 'Undo blur and fix out-of-focus photos',
    description: `Undo blur and fix out-of-focus photos.`,
    url: 'https://focusmagic.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/focusmagic.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 70,
    bookmarks: 18,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(126),
    updatedAt: daysAgo(24),
  },
  {
    id: 'r179',
    slug: 'webinpaint',
    name: 'Webinpaint',
    tagline: 'Remove unwanted elements from photos online',
    description: `Remove unwanted elements from photos online.`,
    url: 'https://webinpaint.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/webinpaint.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 198,
    bookmarks: 28,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(113),
    updatedAt: daysAgo(2),
  },
  {
    id: 'r180',
    slug: 'magic-picture-fx',
    name: 'Magic Picture FX',
    tagline: 'Photo sharpening and file size reduction',
    description: `Photo sharpening and file size reduction.`,
    url: 'https://magicpicture.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/magicpicture.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 31,
    bookmarks: 37,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(106),
    updatedAt: daysAgo(19),
  },
  {
    id: 'r181',
    slug: 'touchretouch-for-mac',
    name: 'TouchRetouch for Mac',
    tagline: 'Desktop object removal for Mac',
    description: `Desktop object removal for Mac.`,
    url: 'https://www.touchretouch.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.touchretouch.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 126,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(131),
    updatedAt: daysAgo(4),
  },
  {
    id: 'r182',
    slug: 'photoacute',
    name: 'PhotoAcute',
    tagline: 'Geometric distortion and noise correction',
    description: `Geometric distortion and noise correction.`,
    url: 'https://photoacute.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photoacute.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 86,
    bookmarks: 20,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(59),
    updatedAt: daysAgo(28),
  },
  {
    id: 'r184',
    slug: 'gthumb',
    name: 'gThumb',
    tagline: 'Image viewer and browser for Linux',
    description: `Image viewer and browser for Linux.`,
    url: 'https://gthumb.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/gthumb.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 229,
    bookmarks: 17,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(81),
    updatedAt: daysAgo(11),
  },
  {
    id: 'r185',
    slug: 'nomacs',
    name: 'nomacs',
    tagline: 'Free open-source image viewer',
    description: `Free open-source image viewer.`,
    url: 'https://nomacs.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/nomacs.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 150,
    bookmarks: 14,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(23),
  },
  {
    id: 'r186',
    slug: 'google-photos',
    name: 'Google Photos',
    tagline: 'Free photo backup and organization',
    description: `Free photo backup and organization.`,
    url: 'https://www.photos.google.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/photos.google.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 136,
    bookmarks: 19,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(99),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r187',
    slug: 'faststone-image-viewer',
    name: 'FastStone Image Viewer',
    tagline: 'Fast image browser, converter and editor',
    description: `Fast image browser, converter and editor.`,
    url: 'https://faststone.org',
    logoUrl: 'https://icons.duckduckgo.com/ip3/faststone.org.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 192,
    bookmarks: 46,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(141),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r188',
    slug: 'acdsee',
    name: 'ACDSee',
    tagline: 'Photo manager, editor and RAW processor',
    description: `Photo manager, editor and RAW processor.`,
    url: 'https://www.acdsee.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.acdsee.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 70,
    bookmarks: 23,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r189',
    slug: 'auslogics-duplicate-finder',
    name: 'Auslogics Duplicate Finder',
    tagline: 'Duplicate image finder',
    description: `Duplicate image finder.`,
    url: 'https://www.auslogics.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.auslogics.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 88,
    bookmarks: 28,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(298),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r190',
    slug: 'irfanview',
    name: 'Irfanview',
    tagline: 'Image viewer with batch editing',
    description: `Image viewer with batch editing.`,
    url: 'https://www.irfanview.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.irfanview.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 123,
    bookmarks: 52,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(217),
    updatedAt: daysAgo(26),
  },
  {
    id: 'r192',
    slug: 'pixbuf',
    name: 'Pixbuf',
    tagline: 'Photo sharing and selling platform',
    description: `Photo sharing and selling platform.`,
    url: 'https://pixbuf.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pixbuf.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 117,
    bookmarks: 18,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(196),
    updatedAt: daysAgo(8),
  },
  {
    id: 'r193',
    slug: 'xnview-mp',
    name: 'XnView MP',
    tagline: 'Cross-platform image viewer and organizer',
    description: `Cross-platform image viewer and organizer.`,
    url: 'https://www.xnview.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.xnview.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 60,
    bookmarks: 22,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r194',
    slug: 'prodibi',
    name: 'Prodibi',
    tagline: 'Professional photo display platform',
    description: `Professional photo display platform.`,
    url: 'https://prodibi.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/prodibi.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 103,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(293),
    updatedAt: daysAgo(7),
  },
  {
    id: 'r195',
    slug: 'photo-mechanic',
    name: 'Photo Mechanic',
    tagline: 'Speed photo processing and metadata platform',
    description: `Speed photo processing and metadata platform.`,
    url: 'https://www.camerabits.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.camerabits.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 212,
    bookmarks: 26,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(105),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r198',
    slug: 'batchphoto',
    name: 'BatchPhoto',
    tagline: 'Batch photo editing and processing',
    description: `Batch photo editing and processing.`,
    url: 'https://www.batchphoto.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.batchphoto.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 147,
    bookmarks: 51,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(51),
    updatedAt: daysAgo(17),
  },
  {
    id: 'r199',
    slug: 'hugin',
    name: 'Hugin',
    tagline: 'Open-source panorama photo stitcher',
    description: `Open-source panorama photo stitcher.`,
    url: 'https://hugin.sourceforge.net',
    logoUrl: 'https://icons.duckduckgo.com/ip3/hugin.sourceforge.net.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 46,
    bookmarks: 16,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(228),
    updatedAt: daysAgo(20),
  },
  {
    id: 'r200',
    slug: 'image-composite-editor',
    name: 'Image Composite Editor',
    tagline: 'Microsoft panoramic image stitcher',
    description: `Microsoft panoramic image stitcher.`,
    url: 'https://www.microsoft.com/en-us/research',
    logoUrl: 'https://icons.duckduckgo.com/ip3/www.microsoft.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 36,
    bookmarks: 42,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(66),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r201',
    slug: 'svenstork',
    name: 'Svenstork',
    tagline: 'Photoshop luminosity masking extension',
    description: `Photoshop luminosity masking extension.`,
    url: 'https://svenstork.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/svenstork.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 110,
    bookmarks: 39,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(69),
    updatedAt: daysAgo(5),
  },
  {
    id: 'r202',
    slug: 'lrtimelapse',
    name: 'LRTimelapse',
    tagline: 'Comprehensive time lapse editing solution',
    description: `Comprehensive time lapse editing solution.`,
    url: 'https://lrtimelapse.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/lrtimelapse.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 95,
    bookmarks: 22,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(169),
    updatedAt: daysAgo(27),
  },
  {
    id: 'r203',
    slug: 'pixinsight',
    name: 'PixInsight',
    tagline: 'Professional astrophotography processing',
    description: `Professional astrophotography processing.`,
    url: 'https://pixinsight.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pixinsight.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 38,
    bookmarks: 26,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(197),
    updatedAt: daysAgo(22),
  },
  {
    id: 'r204',
    slug: 'deepskystacker',
    name: 'DeepSkyStacker',
    tagline: 'Freeware astrophotography stacking',
    description: `Freeware astrophotography stacking.`,
    url: 'https://deepskystacker.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/deepskystacker.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 156,
    bookmarks: 16,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(204),
    updatedAt: daysAgo(1),
  },
  {
    id: 'r205',
    slug: 'pixaflux',
    name: 'PixaFlux',
    tagline: 'Node-based PBR texture composer',
    description: `Node-based PBR texture composer.`,
    url: 'https://pixaflux.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/pixaflux.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 131,
    bookmarks: 22,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(147),
    updatedAt: daysAgo(30),
  },
  {
    id: 'r206',
    slug: 'gigapan',
    name: 'Gigapan',
    tagline: 'Create huge panoramic images',
    description: `Create huge panoramic images.`,
    url: 'https://gigapan.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/gigapan.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 36,
    bookmarks: 52,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(66),
    updatedAt: daysAgo(25),
  },
  {
    id: 'r209',
    slug: 'stereophoto-maker',
    name: 'StereoPhoto Maker',
    tagline: 'Stereoscopic 3D photo editor and viewer',
    description: `Stereoscopic 3D photo editor and viewer.`,
    url: 'https://stereophotomaker.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/stereophotomaker.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 147,
    bookmarks: 8,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(319),
    updatedAt: daysAgo(28),
  },
  {
    id: 'r210',
    slug: 'imagej',
    name: 'ImageJ',
    tagline: 'Java-based scientific image processing',
    description: `Java-based scientific image processing.`,
    url: 'https://imagej.net',
    logoUrl: 'https://icons.duckduckgo.com/ip3/imagej.net.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 56,
    bookmarks: 57,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(6),
  },
  {
    id: 'r215',
    slug: 'virtualrig-studio',
    name: 'VirtualRig Studio',
    tagline: 'Realistic motion blur simulation software',
    description: `Realistic motion blur simulation software.`,
    url: 'https://virtualrig.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/virtualrig.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'paid',
    upvotes: 202,
    bookmarks: 9,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(297),
    updatedAt: daysAgo(9),
  },
  {
    id: 'r216',
    slug: 'unfade-photo-scanner',
    name: 'Unfade Photo Scanner',
    tagline: 'Photo album scanner app for iOS',
    description: `Photo album scanner app for iOS.`,
    url: 'https://unfade.com',
    logoUrl: 'https://icons.duckduckgo.com/ip3/unfade.com.ico',
    category: 'image-editing',
    tags: ['photo', 'editing', 'image'],
    pricing: 'free',
    upvotes: 210,
    bookmarks: 24,
    submittedBy: 'u1',
    featured: false,
    createdAt: daysAgo(119),
    updatedAt: daysAgo(26),
  },

]
